name: programacao_reativa
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  rxdart: ^0.23.1
#  path: ^1.6.0

dev_dependencies:

